spring.application.name=ClinicBooking
spring.profiles.active=dev

server.port=8080
server.forward-headers-strategy=framework

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true



