spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
management.endpoints.web.exposure.include=health

# JWT secret
jwt.secret=${JWT_SECRET}

# CORS cho FE prod
app.cors.allowed-origins=https://fe.qlba.com
