spring.application.name=ClinicBooking
spring.profiles.active=dev

server.port=8080
server.forward-headers-strategy=framework

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

spring.jackson.time-zone=Asia/Ho_Chi_Minh

google.cloud.storage.service-account-key-path=classpath:firebase-service-account.json
app.firebase-config=firebase-service-account.json
app.firebase-project-id = clinicbooking-6a8e3

supabase.url=${SUPABASE_URL}
supabase.service-key=${SUPABASE_SERVICE_KEY}
supabase.storage-bucket-name=${SUPABASE_STORAGE_BUCKETNAME}
supabase.storage-base-url=${supabase.url}/storage/v1/object/public/${supabase.storage-bucket-name}

# Gemini AI Configuration
gemini.api.key=${GEMINI_API_KEY}
gemini.api.model=gemini-2.5-flash
gemini.api.url=https://generativelanguage.googleapis.com/v1beta

# SEPAY Configuration
sepay.api.key=${SEPAY_API_KEY}
sepay.account.number=${SEPAY_ACCOUNT_NUMBER}
sepay.account.name=${SEPAY_ACCOUNT_NAME}
sepay.bank.code=${SEPAY_BANK_CODE}
sepay.bank.name=${SEPAY_BANK_NAME}


